library(dplyr)
library(tidyr)
library(sqldf)
setwd("C:/Users/slc404/OneDrive - Sherwin-Williams/Rprojects/Coursera/Exploratory Data Analysis/Week 1")
data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date == '1/2/2007' ", header = TRUE, sep = ";")
data2 <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date == '2/2/2007' ", header = TRUE, sep = ";")
data<-rbind(data, data2)
png('plot2.png', width = 480, height = 480)
data$DateTime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
plot2<-plot(data$DateTime, data$Global_active_power, ylab="Global Active Power (kilowatts)", type="l", xlab = "")
dev.off()