library(dplyr)
library(tidyr)
library(sqldf)
setwd("C:/Users/slc404/OneDrive - Sherwin-Williams/Rprojects/Coursera/Exploratory Data Analysis/Week 1")
data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date == '1/2/2007' ", header = TRUE, sep = ";")
data2 <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date == '2/2/2007' ", header = TRUE, sep = ";")
data<-rbind(data, data2)
png('plot4.png', width = 480, height = 480)
data$DateTime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(data$DateTime, data$Global_active_power, ylab="Global Active Power (kilowatts)", type="l", xlab = "")
plot(data$DateTime, data$Voltage, ylab="Voltage", type="l", xlab = "datetime")
plot(data$DateTime, data$Sub_metering_1,  type="l", ylab = "Energy sub metering", xlab="")
lines(data$DateTime, data$Sub_metering_2, type = "l", col = "red")
lines(data$DateTime, data$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(data$DateTime, data$Global_reactive_power, ylab="Global_reactive_power", type="l", xlab = "datetime")
dev.off()
plot4<-hist(data$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", main = "Gloabal Active Power")
dev.off()